### ISSUE TITLE
AttentionPool missing and suggestion

### ISSUE THREAD

**Issue by ciroraggio** [pfriedri/cwdm#1]
Hi,
thanks for the great work! I noticed that in the [unet.py](https://github.com/pfriedri/cwdm/blob/main/guided_diffusion/unet.py) the import of the AttentionPool2d layer is missing. 
Maybe you are using the AttentionPool2d layer from [this module](https://github.com/huggingface/pytorch-image-models/blob/main/timm/layers/attention_pool2d.py)?
If so, could you include a reference? If not, I think it would be useful to include the correct implementation.

Thanks again!  😃

**Comment by pfriedri** [comment]
@ciroraggio Thanks for pointing that out. The `AttentionPool2d` layer is just used in the `EncoderUNetModel` that we do not use at all (it's just a leftover from the code-base I used).

**Comment by ciroraggio** [comment]
@pfriedri but it could still be useful to someone as it is well written. You could at least think about adding a reference for those who are not so familiar with it. 
However, since it's not a problem for the project in general, I'll close this issue.
Thank you very much! 👍
